version: '3.8'

services:
  eureka-service:
    build:
      context: ./service-registry
    container_name: eureka-service
    ports:
      - "8761:8761"
    networks:
      - my-network

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER_URL=http://eureka-service:8761/eureka/
    depends_on:
      - eureka-service
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      retries: 3

  book-service:
    build:
      context: ./book-service
    container_name: book-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVER_URL=http://eureka-service:8761/eureka/
    depends_on:
      - eureka-service
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 30s
      retries: 3

networks:
  my-network:
    driver: bridge
